# Generated by Django 2.1.3 on 2019-03-07 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentdate', models.DateField()),
                ('appointmenttime', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'appointments',
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completedTime', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.Appointment')),
            ],
            options={
                'verbose_name_plural': 'appointmentdetails',
                'db_table': 'appointmentdetail',
            },
        ),
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=255)),
                ('partsprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laborprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicedescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'carservices',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclemake', models.CharField(max_length=255)),
                ('vehiclemodel', models.CharField(max_length=255)),
                ('licenseplate', models.CharField(max_length=15)),
                ('licensestate', models.CharField(max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vehicles',
                'db_table': 'vehicle',
            },
        ),
        migrations.AddField(
            model_name='appointmentdetail',
            name='carservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.CarService'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.Vehicle'),
        ),
    ]
