# Generated by Django 2.1.3 on 2019-03-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicleyear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
